export const AUTH_SERVICE = "AUTH_SERVICE";
export const NOTIFICATION_SERVICE = "NOTIFICATION_SERVICE";
export const STOCK_SERVICE = "STOCK_SERVICE";

export const SERVICES = {
	AUTH: AUTH_SERVICE,
	NOTIFICATION: NOTIFICATION_SERVICE,
	STOCK: STOCK_SERVICE,
};
