entryPoints:
  web:
    address: ':80'
  dashboard:
    address: ':8081'
  nats:
    address: ':8082'

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false
  file:
    directory: '/etc/traefik/dynamic'
    watch: true

log:
  level: DEBUG
