// Email Event Names
export enum EMAIL_EVENT_NAMES {
	USER_NOTIFICATION = "USER_NOTIFICATION",
	NEW_ORDER_SUCCESS = "NEW_ORDER_SUCCESS",
	PAYMENT_CONFIRMATION = "PAYMENT_CONFIRMATION",
	PAYMENT_STATUS = "PAYMENT_STATUS",
	SHIPPING_STATUS = "SHIPPING_STATUS",
}

// Stock Event Names
export enum STOCK_EVENT_NAMES {
	STOCK_ADDED = "STOCK_ADDED",
	SALES_STOCK = "SALES_STOCK",
	RETURN_SALES_STOCK = "RETURN_SALES_STOCK",
}

export const EVENTS = {
	STOCK: STOCK_EVENT_NAMES,
	EMAIL: EMAIL_EVENT_NAMES,
};
